server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route
          uri:  lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_route2
          uri:  lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - After=2020-04-28T16:49:37.720+08:00[Asia/Shanghai]
#            - Cookie=username,yhj
#            - Header=X-Request-Id, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
